spring:  
  application:
    name: sadr-service
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
user.role: walter