eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: service-one
  config:
    import: optional:configserver:http://localhost:8888